# Audio configuration for OMNIS
# This file is automatically generated by configure_speaker.py

# The ALSA card index for the speaker (e.g., 0, 1, 2)
# Auditor results show USB PnP Sound Device is actually on Card 2
SPEAKER_CARD_INDEX = 2
