# Audio configuration for OMNIS
# This file is automatically generated by configure_speaker.py

# The ALSA card index for the speaker (e.g., 0, 1, 2)
# You can find this using 'aplay -l'
SPEAKER_CARD_INDEX = 1
