# Audio configuration for OMNIS
# This file is automatically generated by configure_speaker.py

# The ALSA card index for the speaker (e.g., 0, 1, 2)
# USB PnP Sound Device is on Card 1
SPEAKER_CARD_INDEX = 2
