import os
import subprocess
import re

def list_audio_cards():
    print("Listing available audio playback cards...")
    try:
        # Run aplay -l to get list of cards
        # On Pi, this is the standard way to see hardware cards
        result = subprocess.run(['aplay', '-l'], capture_output=True, text=True)
        if result.returncode != 0:
            print("Error running aplay -l. Make sure alsa-utils is installed.")
            return []
        
        cards = []
        lines = result.stdout.split('\n')
        for line in lines:
            if line.startswith('card'):
                # Format: card 1: Device [USB Audio], device 0: USB Audio [USB Audio]
                match = re.search(r'card (\d+): (.*) \[.*\], device (\d+):', line)
                if match:
                    card_idx = match.group(1)
                    card_name = match.group(2)
                    cards.append({'index': int(card_idx), 'name': card_name})
        return cards
    except FileNotFoundError:
        print("aplay command not found. This script should be run on the Raspberry Pi.")
        return []

def configure():
    cards = list_audio_cards()
    
    if not cards:
        print("No audio cards detected or 'aplay' not available.")
        # Fallback for manual entry
        try:
            val = input("Enter the card index manually (usually 1 for USB): ")
            selected_index = int(val)
        except ValueError:
            print("Invalid input. Defaulting to 1.")
            selected_index = 1
    else:
        print("\nAvailable Speaker Cards:")
        for card in cards:
            print(f"[{card['index']}]: {card['name']}")
        
        # Auto-detect USB card
        usb_cards = [c for c in cards if "USB" in c['name'].upper()]
        default_idx = usb_cards[0]['index'] if usb_cards else cards[0]['index']
        
        print(f"\nRecommended index: {default_idx}")
        user_input = input(f"Select card index (default {default_idx}): ").strip()
        
        if user_input == "":
            selected_index = default_idx
        else:
            try:
                selected_index = int(user_input)
            except ValueError:
                print("Invalid input. Using default.")
                selected_index = default_idx

    print(f"\nConfiguring OMNIS to use ALSA card {selected_index}...")
    
    config_content = f"""# Audio configuration for OMNIS
# This file is automatically generated by configure_speaker.py

# The ALSA card index for the speaker (e.g., 0, 1, 2)
SPEAKER_CARD_INDEX = {selected_index}
"""
    
    with open('audio_config.py', 'w') as f:
        f.write(config_content)
    
    print("✅ Configuration saved to audio_config.py")
    print("\nTo test the speaker, run: python3 speaker.py")

if __name__ == "__main__":
    configure()
