#!/usr/bin/env python3
"""
OMNIS Audio Card Diagnostic and Fix Tool
This script helps diagnose and fix audio output issues after changing cards
"""

import os
import subprocess
import re
import sys

def print_header(text):
    print("\n" + "="*60)
    print(f"  {text}")
    print("="*60)

def list_audio_cards():
    """List all available audio playback cards"""
    print_header("STEP 1: Listing Available Audio Cards")
    
    try:
        result = subprocess.run(['aplay', '-l'], capture_output=True, text=True)
        if result.returncode != 0:
            print("❌ Error running aplay -l. Make sure alsa-utils is installed.")
            return []
        
        print(result.stdout)
        
        cards = []
        lines = result.stdout.split('\n')
        for line in lines:
            if line.startswith('card'):
                # Format: card 1: Device [USB Audio], device 0: USB Audio [USB Audio]
                match = re.search(r'card (\d+): (.*?) \[', line)
                if match:
                    card_idx = int(match.group(1))
                    card_name = match.group(2).strip()
                    if card_idx not in [c['index'] for c in cards]:
                        cards.append({'index': card_idx, 'name': card_name})
        
        return cards
    except FileNotFoundError:
        print("❌ aplay command not found. This script must be run on the Raspberry Pi.")
        return []
    except Exception as e:
        print(f"❌ Error: {e}")
        return []

def test_card(card_index, device_strings=None):
    """Test a specific card with various device strings"""
    if device_strings is None:
        device_strings = [
            f"plughw:{card_index},0",
            f"sysdefault:CARD={card_index}",
            f"hw:{card_index},0",
            f"dmix:CARD={card_index}"
        ]
    
    print(f"\n🔊 Testing Card {card_index}...")
    
    working_strings = []
    
    for ds in device_strings:
        print(f"  Testing: {ds}...", end=" ")
        
        # Use speaker-test for quick audio test
        cmd = f"timeout 3 speaker-test -D {ds} -c2 -t wav -l1 > /dev/null 2>&1"
        ret = os.system(cmd)
        
        if ret == 0:
            print("✅ WORKS!")
            working_strings.append(ds)
        else:
            print(f"❌ Failed (code: {ret})")
    
    return working_strings

def check_volume_levels(card_index):
    """Check if the card is muted or volume is too low"""
    print(f"\n🔊 Checking volume levels for Card {card_index}...")
    
    try:
        # Get mixer controls for the card
        result = subprocess.run(['amixer', '-c', str(card_index), 'scontrols'], 
                              capture_output=True, text=True)
        
        if result.returncode == 0 and result.stdout:
            print(f"  Available controls: {result.stdout.strip()}")
            
            # Try to check PCM volume
            vol_result = subprocess.run(['amixer', '-c', str(card_index), 'get', 'PCM'], 
                                       capture_output=True, text=True)
            if vol_result.returncode == 0:
                print(f"  PCM Volume: {vol_result.stdout}")
                
                # Check if muted
                if '[off]' in vol_result.stdout:
                    print("  ⚠️  WARNING: Card appears to be MUTED!")
                    return False
        
        return True
    except Exception as e:
        print(f"  ⚠️  Could not check volume: {e}")
        return True

def unmute_card(card_index):
    """Attempt to unmute the card"""
    print(f"\n🔊 Attempting to unmute Card {card_index}...")
    
    try:
        # Try to unmute PCM
        os.system(f"amixer -c {card_index} set PCM unmute > /dev/null 2>&1")
        os.system(f"amixer -c {card_index} set PCM 100% > /dev/null 2>&1")
        
        # Try to unmute Master if it exists
        os.system(f"amixer -c {card_index} set Master unmute > /dev/null 2>&1")
        os.system(f"amixer -c {card_index} set Master 100% > /dev/null 2>&1")
        
        print("  ✅ Unmute commands sent")
        return True
    except Exception as e:
        print(f"  ❌ Error: {e}")
        return False

def update_audio_config(card_index):
    """Update audio_config.py with the correct card index"""
    print(f"\n📝 Updating audio_config.py to use Card {card_index}...")
    
    config_content = f"""# Audio configuration for OMNIS
# This file is automatically generated by fix_audio_card.py

# The ALSA card index for the speaker (e.g., 0, 1, 2, 3)
SPEAKER_CARD_INDEX = {card_index}
"""
    
    try:
        with open('audio_config.py', 'w') as f:
            f.write(config_content)
        print(f"  ✅ Configuration saved! Card {card_index} is now set.")
        return True
    except Exception as e:
        print(f"  ❌ Error writing config: {e}")
        return False

def test_with_actual_audio(card_index):
    """Test the card with actual audio playback"""
    print(f"\n🎵 Testing Card {card_index} with actual audio...")
    
    try:
        from gtts import gTTS
        
        # Generate test audio
        test_file = "audio_test_temp.mp3"
        tts = gTTS(text=f"Testing audio on card {card_index}", lang='en')
        tts.save(test_file)
        
        # Try mpg123 first (what OMNIS uses)
        device_str = f"plughw:{card_index},0"
        print(f"  Playing with mpg123 on {device_str}...")
        ret = os.system(f"mpg123 -q -a {device_str} {test_file} > /dev/null 2>&1")
        
        # Clean up
        if os.path.exists(test_file):
            os.remove(test_file)
        
        if ret == 0:
            print("  ✅ Audio playback successful!")
            return True
        else:
            print(f"  ❌ Audio playback failed (code: {ret})")
            return False
            
    except Exception as e:
        print(f"  ❌ Error: {e}")
        return False

def main():
    print_header("OMNIS Audio Card Diagnostic & Fix Tool")
    print("This tool will help you identify and fix audio card issues.\n")
    
    # Step 1: List all cards
    cards = list_audio_cards()
    
    if not cards:
        print("\n❌ No audio cards detected!")
        print("Please check:")
        print("  1. Is your USB speaker/audio device plugged in?")
        print("  2. Run 'lsusb' to see if the USB device is recognized")
        print("  3. Try unplugging and replugging the USB audio device")
        return
    
    # Step 2: Show available cards
    print_header("STEP 2: Available Cards Summary")
    for card in cards:
        print(f"  Card {card['index']}: {card['name']}")
    
    # Step 3: Ask user which card to test/fix
    print_header("STEP 3: Select Card to Test")
    
    # Check current config
    try:
        import audio_config
        current_card = getattr(audio_config, 'SPEAKER_CARD_INDEX', None)
        if current_card is not None:
            print(f"  Current configuration: Card {current_card}")
    except:
        current_card = None
        print("  No current configuration found")
    
    # Auto-detect USB cards
    usb_cards = [c for c in cards if "USB" in c['name'].upper() or "PnP" in c['name']]
    
    if usb_cards:
        print(f"\n  🔍 Detected USB audio device(s):")
        for card in usb_cards:
            print(f"     Card {card['index']}: {card['name']}")
        default_card = usb_cards[0]['index']
    else:
        default_card = cards[-1]['index'] if cards else 1
    
    print(f"\n  Recommended card: {default_card}")
    user_input = input(f"  Enter card number to test (default {default_card}): ").strip()
    
    if user_input == "":
        selected_card = default_card
    else:
        try:
            selected_card = int(user_input)
        except ValueError:
            print("  Invalid input. Using default.")
            selected_card = default_card
    
    # Step 4: Check volume/mute status
    print_header("STEP 4: Checking Volume & Mute Status")
    is_unmuted = check_volume_levels(selected_card)
    
    if not is_unmuted:
        unmute_card(selected_card)
    
    # Step 5: Test the card
    print_header("STEP 5: Testing Audio Output")
    working_strings = test_card(selected_card)
    
    if working_strings:
        print(f"\n✅ Card {selected_card} is working!")
        print(f"   Working device strings: {', '.join(working_strings)}")
        
        # Step 6: Test with actual audio
        print_header("STEP 6: Testing with Actual Audio Playback")
        audio_works = test_with_actual_audio(selected_card)
        
        if audio_works:
            # Step 7: Update config
            print_header("STEP 7: Updating Configuration")
            update_audio_config(selected_card)
            
            print_header("✅ SUCCESS!")
            print(f"  Card {selected_card} is configured and working!")
            print("\n  Next steps:")
            print("    1. Restart OMNIS: python3 main.py")
            print("    2. Test with: python3 test_speaker.py")
        else:
            print("\n⚠️  Card responds to speaker-test but not to mpg123")
            print("   This might be a format/codec issue.")
            print("   Try installing: sudo apt-get install mpg123")
    else:
        print(f"\n❌ Card {selected_card} is not responding to audio tests")
        print("\nPossible issues:")
        print("  1. Card is being used by another process (PulseAudio?)")
        print("  2. USB device needs more power")
        print("  3. Wrong card selected")
        print("\nTroubleshooting steps:")
        print("  • Check what's using the device: fuser -v /dev/snd/*")
        print("  • Kill PulseAudio: pulseaudio -k")
        print("  • Check USB power: lsusb -v | grep -i power")
        print("  • Try a different USB port")

if __name__ == "__main__":
    main()
